Projekt-Biblioteka/Models/Book.cs
using Projekt_Biblioteka.Data.Base;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Projekt_Biblioteka.Models
{
    public class Book : IEntityBase
    {
        [Key]
        public int Id { get; set; }
        public string Title { get; set; }
        public DateTime RelaseDate { get; set; }
        public string Description { get; set; }
        public string ImageURL { get; set; }
        public bool IsBorrowed { get; set; }
        public string ISBN { get; set; }



        //Relationships
        public int PublisherId { get; set; }
        [ForeignKey("PublisherId")]
        public virtual Publisher Publisher { get; set; }

        public int CategoryId { get; set; }
        [ForeignKey("CategoryId")]
        public virtual Category Categories { get; set; }

        public virtual ICollection <Author_Book> Authors_Books { get; set; }



    }
}

Projekt-Biblioteka/Controllers/AuthorController.cs
using Projekt_Biblioteka.Data.Services;
using Projekt_Biblioteka.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Projekt_Biblioteka.Data.Static;
using Microsoft.AspNetCore.Authorization;

namespace Projekt_Biblioteka.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class AuthorController : Controller
    {
        private readonly IAuthorService _service;

        public AuthorController(IAuthorService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index()
        {
            var allAuthors = await _service.GetAllAsync();
            return View(allAuthors);
        }

        //GET: author/details
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var authorDetails = await _service.GetAuthorByIdAsync(id);
            if (authorDetails == null) return View("NotFound");
            return View(authorDetails);
        }

        //GET: author/create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("ImageURL,FullName,Bio")] Author author)
        {
            if (!ModelState.IsValid) return View(author);

            await _service.AddAsync(author);
            return RedirectToAction(nameof(Index));
        }

        //GET: author/edit
        public async Task<IActionResult> Edit(int id)
        {
            var authorDetails = await _service.GetAuthorByIdAsync(id);
            if (authorDetails == null) return View("NotFound");
            return View(authorDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, Author author)
        {
            if (!ModelState.IsValid) return View(author);

            if (id == author.Id)
            {
                await _service.UpdateAsync(id, author);
                return RedirectToAction(nameof(Index));
            }
            return View(author);
        }

        //GET: author/delete
        public async Task<IActionResult> Delete(int id)
        {
            var authorDetails = await _service.GetAuthorByIdAsync(id);
            if (authorDetails == null) return View("NotFound");
            return View(authorDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeletePost(int id)
        {
            var authorDetails = await _service.GetAuthorByIdAsync(id);
            if (authorDetails == null) return View("NotFound");

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Projekt-Biblioteka/Controllers/CategoryController.cs
using Projekt_Biblioteka.Data.Services;
using Projekt_Biblioteka.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Projekt_Biblioteka.Data.Static;
using Microsoft.AspNetCore.Authorization;

namespace Projekt_Biblioteka.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class CategoryController : Controller
    {
        private readonly ICategoryService _service;

        public CategoryController(ICategoryService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index()
        {
            var allCategories = await _service.GetAllAsync();
            return View(allCategories);
        }

        //GET: category/details
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var categoryDetails = await _service.GetCategoryByIdAsync(id);
            if (categoryDetails == null) return View("NotFound");
            return View(categoryDetails);
        }

        //GET: category/create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Category category)
        {
            if (!ModelState.IsValid) return View(category);

            await _service.AddAsync(category);
            return RedirectToAction(nameof(Index));
        }

        //GET: category/edit
        public async Task<IActionResult> Edit(int id)
        {
            var categoryDetails = await _service.GetCategoryByIdAsync(id);
            if (categoryDetails == null) return View("NotFound");
            return View(categoryDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, Category category)
        {
            if (!ModelState.IsValid) return View(category);

            if (id == category.Id)
            {
                await _service.UpdateAsync(id, category);
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        //GET: category/delete
        public async Task<IActionResult> Delete(int id)
        {
            var categoryDetails = await _service.GetCategoryByIdAsync(id);
            if (categoryDetails == null) return View("NotFound");
            return View(categoryDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeletePost(int id)
        {
            var categoryDetails = await _service.GetCategoryByIdAsync(id);
            if (categoryDetails == null) return View("NotFound");

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Projekt-Biblioteka/Controllers/OrderController.cs
using Projekt_Biblioteka.Data.Cart;
using Projekt_Biblioteka.Data.Services;
using Projekt_Biblioteka.Data.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using System.Threading.Tasks;
using Projekt_Biblioteka.Data.Static;

namespace Projekt_Biblioteka.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private readonly IBookService _bookService;
        private readonly BookCart _bookCart;
        private readonly IOrderService _orderService;

        public OrderController(IBookService bookService, BookCart bookCart, IOrderService orderService)
        {
            _bookService = bookService;
            _bookCart = bookCart;
            _orderService = orderService;
        }

        public async Task<IActionResult> Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);

            var orders = await _orderService.GetOrdersByUserIdAndRoleAsync(userId, userRole);
            return View(orders);
        }
        
        //BookCart
        public IActionResult BookCart()
        {
            var items = _bookCart.GetBookCartItems();
            _bookCart.BookCartItems = items;

            var response = new BookCartVM()
            {
                bookCart = _bookCart
            };

            return View(response);
        }
        //Add item
        public async Task<RedirectToActionResult> AddItemToBookCart(int id)
        {
            var item = await _bookService.GetBookByIdAsync(id);

            if (item != null)
            {
                _bookCart.AddItemToCart(item);
            }
            return RedirectToAction(nameof(BookCart));
        }
        //Remove item
        public async Task<IActionResult> RemoveItemFromBookCart(int id)
        {
            var item = await _bookService.GetBookByIdAsync(id);

            if (item != null)
            {
                _bookCart.RemoveItemFromCart(item);
            }
            return RedirectToAction(nameof(BookCart));
        }

        //CompleteOrder
        public async Task<IActionResult> CompleteOrder()
        {
            var items = _bookCart.GetBookCartItems();
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userEmailAddress = User.FindFirstValue(ClaimTypes.Email);

            await _orderService.StoreOrderAsync(items, userId, userEmailAddress);
            await _bookCart.ClearBookCartAsync();
            foreach (var borrow in items)
            {
                await _bookCart.BorrowedStatus(borrow);
            }

            return View("CompleteOrder");
        }
    }
}

Projekt-Biblioteka/Controllers/PublisherController.cs
using Projekt_Biblioteka.Data.Services;
using Projekt_Biblioteka.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Projekt_Biblioteka.Data.Static;
using Microsoft.AspNetCore.Authorization;

namespace Projekt_Biblioteka.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class PublisherController : Controller
    {
        private readonly IPublisherService _service;

        public PublisherController(IPublisherService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index()
        {
            var allPublishers = await _service.GetAllAsync();
            return View(allPublishers);
        }

        //GET: publisher/details
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var publisherDetails = await _service.GetPublisherByIdAsync(id);
            if (publisherDetails == null) return View("NotFound");
            return View(publisherDetails);
        }

        //GET: publisher/create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("ImageURL,Name,Description")] Publisher publisher)
        {
            if (!ModelState.IsValid) return View(publisher);

            await _service.AddAsync(publisher);
            return RedirectToAction(nameof(Index));
        }

        //GET: publisher/edit
        public async Task<IActionResult> Edit(int id)
        {
            var publisherDetails = await _service.GetPublisherByIdAsync(id);
            if (publisherDetails == null) return View("NotFound");
            return View(publisherDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, Publisher publisher)
        {
            if (!ModelState.IsValid) return View(publisher);

            if (id == publisher.Id)
            {
                await _service.UpdateAsync(id, publisher);
                return RedirectToAction(nameof(Index));
            }
            return View(publisher);
        }

        //GET: publisher/delete
        public async Task<IActionResult> Delete(int id)
        {
            var publisherDetails = await _service.GetPublisherByIdAsync(id);
            if (publisherDetails == null) return View("NotFound");
            return View(publisherDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeletePost(int id)
        {
            var publisherDetails = await _service.GetPublisherByIdAsync(id);
            if (publisherDetails == null) return View("NotFound");

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Projekt-Biblioteka/Views/Book/Create.cshtml
@model NewBookVM
@using Projekt_Biblioteka.Data.ViewModels;

@{
    ViewData["Title"] = "Dodaj Książke";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <p>
            <h4 class="text-center">Dodaj Książkę</h4>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Title" class="control-label"></label>
                                <input asp-for="Title" class="form-control" />
                                <span asp-validation-for="Title" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ISBN" class="control-label"></label>
                                <input asp-for="ISBN" class="form-control" />
                                <span asp-validation-for="ISBN" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="RelaseDate" class="control-label"></label>
                                <input asp-for="RelaseDate" type="date" class="form-control" />
                                <span asp-validation-for="RelaseDate" class="text-danger"></span>
                            </div>
                            <div class="form-check">
                                <input asp-for="IsBorrowed" class="form-check-input" type="checkbox" />
                                <label asp-for="IsBorrowed" class="form-check-label"></label>
                                <span asp-validation-for="IsBorrowed" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="AuthorId" class="control-label"></label>
                                <select id="AuthorSelect" asp-for="AuthorId" class="form-control" asp-items="ViewBag.Authors"></select>
                                <span asp-validation-for="AuthorId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="PublisherId" class="control-label"></label>
                                <select id="PublisherSelect" asp-for="PublisherId" class="form-control" asp-items="ViewBag.Publishers"></select>
                                <span asp-validation-for="PublisherId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="CategoryId" class="control-label"></label>
                                <select id="CategorySelect" asp-for="CategoryId" class="form-control" asp-items="ViewBag.Categories"></select>
                                <span asp-validation-for="CategoryId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ImageURL" class="control-label"></label>
                                <input asp-for="ImageURL" class="form-control" />
                                <span asp-validation-for="ImageURL" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label asp-for="Description" class="control-label"></label>
                                <textarea asp-for="Description" class="form-control"></textarea>
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 offset-4 text-center">
                        <img width="100%" id="ImagePreview" />
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-outline-success float-right" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Wróć</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script>
        $(function () {
            $("#AuthorSelect").select2();
        });
        $(function () {
            $("#PublisherSelect").select2();
        });
        $(function () {
            $("#CategorySelect").select2();
        });
    </script>
    <script>

        $(document).ready(function () {
            var output = document.getElementById('ImagePreview');
            output.src = $("#ImageURL").val();
        })

        $("#ImageURL").on("change", function () {
            var output = document.getElementById('ImagePreview');
            output.src = $(this).val();
        })
    </script>
}

Projekt-Biblioteka/Views/Book/Delete.cshtml
@model NewBookVM
@using Projekt_Biblioteka.Data.ViewModels;

@{
    ViewData["Title"] = "Usuń Książke";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <p>
            <h4 class="text-center">Usuń @Model.Title</h4>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Delete">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Title" class="control-label"></label>
                                <input asp-for="Title" class="form-control" readonly />
                                <span asp-validation-for="Title" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ISBN" class="control-label"></label>
                                <input asp-for="ISBN" class="form-control" readonly />
                                <span asp-validation-for="ISBN" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="RelaseDate" class="control-label"></label>
                                <input asp-for="RelaseDate" type="date" class="form-control" readonly />
                                <span asp-validation-for="RelaseDate" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ImageURL" class="control-label"></label>
                                <input asp-for="ImageURL" class="form-control" readonly />
                                <span asp-validation-for="ImageURL" class="text-danger"></span>
                            </div>
                            <div class="form-check">
                                <input asp-for="IsBorrowed" class="form-check-input" type="checkbox" readonly />
                                <label asp-for="IsBorrowed" class="form-check-label"></label>
                                <span asp-validation-for="IsBorrowed" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="AuthorId" class="control-label"></label>
                                <select asp-for="AuthorId" class="form-control" asp-items="ViewBag.Authors" readonly></select>
                                <span asp-validation-for="AuthorId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="PublisherId" class="control-label"></label>
                                <select asp-for="PublisherId" class="form-control" asp-items="ViewBag.Publishers" readonly></select>
                                <span asp-validation-for="PublisherId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="CategoryId" class="control-label"></label>
                                <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.Categories" readonly></select>
                                <span asp-validation-for="CategoryId" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label asp-for="Description" class="control-label"></label>
                                <textarea asp-for="Description" class="form-control" readonly></textarea>
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 offset-4 text-center">
                        <img width="100%" id="ImageUrlPreview" />
                    </div>
                    <div class="form-group">
                        <form asp-action="Delete">
                            <input type="hidden" asp-for="Id" />
                            <input type="submit" value="Potwierdź" class="btn btn-danger float-right" />
                        </form>
                        <a class="btn btn-outline-secondary" asp-action="Index">Wróć</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

Projekt-Biblioteka/Views/Book/Details.cshtml
@model Book

@{
    ViewData["Title"] = "Movie details";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <div class="card mb-12">
            <div class="row g-0">
                <div class="col-md-12">
                    <div class="card-header">

                            <p class="card-text">
                                <h1 class="card-title">
                                    @Model.Title
                                </h1>
                            </p>
                    </div>
                </div>
                <div class="col-md-4">
                    <img src="@Model.ImageURL" width="100%" alt="@Model.Title">
                </div>
                <div class="col-md-7">
                    <div class="card-body">
                        <p class="card-text">
                            <b>Autor: </b>
                            @foreach (var author in @Model.Authors_Books)
                            {
                                <a asp-controller="Author" asp-action="Details" asp-route-id="@author.AuthorId">
                                    @author.Author.FullName
                                </a>
                            }
                        </p>
                        <p class="card-text">
                            <b>Wydawca: </b>
                            <a asp-controller="Publisher" asp-action="Details" asp-route-id="@Model.PublisherId">
                                @Model.Publisher.Name
                            </a>
                        </p>
                        <p class="card-text">
                            <b>Gatunek: </b>
                            <a asp-controller="Category" asp-action="Details" asp-route-id="@Model.CategoryId">
                                @Model.Categories.Name
                                </a>
                        </p>
                        <p class="card-text"><b>Rok wydania: </b>@Model.RelaseDate.ToString("yyyy")</p>
                        <p class="card-text"><b>ISBN: </b>@Model.ISBN</p>
                        <p class="card-text">
                            @if (!@Model.IsBorrowed != true)
                            {
                                <span class="badge btn-lg bg-danger text-white">WYPOŻYCZONA</span>

                            }
                            else
                            {
                                <span class="badge btn-lg bg-success text-white">DOSTĘPNA</span>
                            }
                        </p>
                        <p class="card-text">@Model.Description</p>
                    </div>
                </div>           
                <div class="col-md-12">
                    <div class="card-footer">
                        <p class="card-text">
                            <a class="btn btn-outline-primary" asp-action="Index">
                                Wróć
                            </a>
                            @if (Model.IsBorrowed != false)
                            {
                                <button type"button" class="btn btn-danger text-white float-right" disabled>Wypożyczone</button>
                            }
                            else
                            {
                            <a class="btn btn-success text-white float-right" asp-controller="Order" asp-action="AddItemToBookCart" asp-route-id="@Model.Id"><i class="bi bi-book"></i> Wypożycz</a>
                            }
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Projekt-Biblioteka/Views/Book/Index.cshtml
@model IEnumerable<Book>

@{
    ViewData["Title"] = "List of Movies";
}

@foreach (var item in Model)
{
    <div class="row">
        <div class="card mb-3" style="width: 100%;">
            <div class="row no-gutters">
                <div class="col-3 col-md-2 col-xl-1">
                    <img src="@item.ImageURL" height="100%" width="100%" alt="@item.Title">
                </div>
                <div class="col-9 col-md-10 col-xl-11">
                    <div class="card-body">
                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <a class="float-right mx-2" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i></a>
                            <a class="float-right" asp-action="Delete" asp-route-id="@item.Id"><i class="bi bi-trash"></i></a>
                        }
                            <h1 class="card-text">@item.Title</h1>
                            @if (item.IsBorrowed != false)
                            {
                                <span class="badge btn-lg bg-danger text-white">WYPOŻYCZONA</span>

                            }
                            else
                            {
                                <span class="badge btn-lg bg-success text-white">DOSTĘPNA</span>
                            }
                            <p class="card-text">
                                <b>Autor: </b>
                                @foreach (var author in item.Authors_Books)
                                {
                                    <a asp-controller="Author" asp-action="Details" asp-route-id="@author.AuthorId">
                                        @author.Author.FullName
                                    </a>
                                }
                            </p>
                            <p class="card-text">
                                <b>Wydawca: </b>
                                <a asp-controller="Publisher" asp-action="Details" asp-route-id="@item.Publisher.Id">@item.Publisher.Name </a>
                            </p>
                            <p class="card-text">
                                <b>Gatuenk: </b>
                                <a asp-controller="Category" asp-action="Details" asp-route-id="@item.Categories.Id">@item.Categories.Name </a>
                            </p>
                        </div>
                </div>
                <div class="col-md-12">
                    <div class="card-footer ">
                        <p class="card-text">
                            <a class="btn btn-outline-primary" asp-action="Details" asp-route-id="@item.Id">
                                <i class="bi bi-eye-fill"></i> Więcej
                            </a>
                            @if (item.IsBorrowed != false)
                            {
                                <button type"button" class="btn btn-danger text-white float-right" disabled>Wypożyczone</button>
                            }
                            else
                            {
                                <a class="btn btn-success text-white float-right" asp-controller="Order" asp-action="AddItemToBookCart" asp-route-id="@item.Id"><i class="bi bi-book"></i> Wypożycz</a>
                            }
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
}