Projekt-Biblioteka/Controllers/AuthorController.cs
using Projekt_Biblioteka.Data.Services;
using Projekt_Biblioteka.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Projekt_Biblioteka.Data.Static;
using Microsoft.AspNetCore.Authorization;

namespace Projekt_Biblioteka.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class AuthorController : Controller
    {
        private readonly IAuthorService _service;

        public AuthorController(IAuthorService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index()
        {
            var allAuthors = await _service.GetAllAsync();
            return View(allAuthors);
        }

        //GET: author/details
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var authorDetails = await _service.GetAuthorByIdAsync(id);
            if (authorDetails == null) return View("NotFound");
            return View(authorDetails);
        }

        //GET: author/create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("ImageURL,FullName,Bio")] Author author)
        {
            if (!ModelState.IsValid) return View(author);

            await _service.AddAsync(author);
            return RedirectToAction(nameof(Index));
        }

        //GET: author/edit
        public async Task<IActionResult> Edit(int id)
        {
            var authorDetails = await _service.GetAuthorByIdAsync(id);
            if (authorDetails == null) return View("NotFound");
            return View(authorDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, Author author)
        {
            if (!ModelState.IsValid) return View(author);

            if (id == author.Id)
            {
                await _service.UpdateAsync(id, author);
                return RedirectToAction(nameof(Index));
            }
            return View(author);
        }

        //GET: author/delete
        public async Task<IActionResult> Delete(int id)
        {
            var authorDetails = await _service.GetAuthorByIdAsync(id);
            if (authorDetails == null) return View("NotFound");
            return View(authorDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeletePost(int id)
        {
            var authorDetails = await _service.GetAuthorByIdAsync(id);
            if (authorDetails == null) return View("NotFound");

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Projekt-Biblioteka/Controllers/BookController.cs
using Projekt_Biblioteka.Data.Services;
using Projekt_Biblioteka.Data.ViewModels;
using Projekt_Biblioteka.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Projekt_Biblioteka.Data.Static;
using Microsoft.AspNetCore.Authorization;

namespace Projekt_Biblioteka.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class BookController : Controller
    {
        private readonly IBookService _service;

        public BookController(IBookService service)
        {
            _service = service;
        }
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var allBooks = await _service.GetAllBooksAsync();
            
            return View(allBooks);
        }

        //Filter
        [AllowAnonymous]
        public async Task<IActionResult> Filter(string searchString)
        {
            var allBooks = await _service.GetAllBooksAsync();

            if (!string.IsNullOrEmpty(searchString))
            {
                var filteredResult = allBooks.Where(n => n.Title.ToLower().Contains(searchString.ToLower()) || n.Authors_Books.Select(n => n.Author.FullName.ToLower()).Contains(searchString.ToLower())).ToList();
                return View("Index", filteredResult);
            }

            return View("Index", allBooks);
        }

        //GET: Book/Details
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var bookDetails = await _service.GetBookByIdAsync(id);
            return View(bookDetails);
        }

        //GET: Book/Create
        public async Task<IActionResult> CreateAsync()
        {
            var bookDropDown = await _service.GetNewBookDropdownsValues();

            ViewBag.Authors = new SelectList(bookDropDown.Authors, "Id", "FullName");
            ViewBag.Publishers = new SelectList(bookDropDown.Publishers, "Id", "Name");
            ViewBag.Categories = new SelectList(bookDropDown.Categories, "Id", "Name");

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(NewBookVM book)
        {
            if (!ModelState.IsValid)
            {
                var bookDropDown = await _service.GetNewBookDropdownsValues();

                ViewBag.Authors = new SelectList(bookDropDown.Authors, "Id", "FullName");
                ViewBag.Publishers = new SelectList(bookDropDown.Publishers, "Id", "Name");
                ViewBag.Categories = new SelectList(bookDropDown.Categories, "Id", "Name");

                return View(book);
            }

            await _service.AddNewBookAsync(book);
            return RedirectToAction(nameof(Index));
        }

        //GET: Book/Edit
        public async Task<IActionResult> Edit(int id)
        {
            var bookDetails = await _service.GetBookByIdAsync(id);
            if (bookDetails == null) return View("NotFound");

            var response = new NewBookVM()
            {
                Id = bookDetails.Id,
                Title = bookDetails.Title,
                Description = bookDetails.Description,
                RelaseDate = bookDetails.RelaseDate,
                ImageURL = bookDetails.ImageURL,
                ISBN = bookDetails.ISBN,
                IsBorrowed = bookDetails.IsBorrowed,
                CategoryId = bookDetails.CategoryId,
                PublisherId = bookDetails.PublisherId,
                AuthorId = bookDetails.Authors_Books.Select(n => n.AuthorId).ToList(),
            };

            var bookDropDown = await _service.GetNewBookDropdownsValues();
            ViewBag.Authors = new SelectList(bookDropDown.Authors, "Id", "FullName");
            ViewBag.Publishers = new SelectList(bookDropDown.Publishers, "Id", "Name");
            ViewBag.Categories = new SelectList(bookDropDown.Categories, "Id", "Name");

            return View(response);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, NewBookVM movie)
        {
            if (id != movie.Id) return View("NotFound");

            if (!ModelState.IsValid)
            {
                var bookDropDown = await _service.GetNewBookDropdownsValues();
                ViewBag.Authors = new SelectList(bookDropDown.Authors, "Id", "FullName");
                ViewBag.Publishers = new SelectList(bookDropDown.Publishers, "Id", "Name");
                ViewBag.Categories = new SelectList(bookDropDown.Categories, "Id", "Name");
                return View(movie);
            }

            await _service.UpdateBookAsync(movie);
            return RedirectToAction(nameof(Index));
        }

        //GET: Book/Delete
        public async Task<IActionResult> Delete(int id)
        {
            var bookDetails = await _service.GetBookByIdAsync(id);
            if (bookDetails == null) return View("NotFound");

            var response = new NewBookVM()
            {
                Id = bookDetails.Id,
                Title = bookDetails.Title,
                Description = bookDetails.Description,
                RelaseDate = bookDetails.RelaseDate,
                ImageURL = bookDetails.ImageURL,
                ISBN = bookDetails.ISBN,
                IsBorrowed = bookDetails.IsBorrowed,
                CategoryId = bookDetails.CategoryId,
                PublisherId = bookDetails.PublisherId,
                AuthorId = bookDetails.Authors_Books.Select(n => n.AuthorId).ToList(),
            };

            var bookDropDown = await _service.GetNewBookDropdownsValues();
            ViewBag.Authors = new SelectList(bookDropDown.Authors, "Id", "FullName");
            ViewBag.Publishers = new SelectList(bookDropDown.Publishers, "Id", "Name");
            ViewBag.Categories = new SelectList(bookDropDown.Categories, "Id", "Name");

            return View(response);
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeletePost(int id)
        {
            var bookDetails = await _service.GetBookByIdAsync(id);
            if (bookDetails == null) return View("NotFound");

            var response = new NewBookVM()
            {
                Id = bookDetails.Id,
                Title = bookDetails.Title,
                Description = bookDetails.Description,
                RelaseDate = bookDetails.RelaseDate,
                ImageURL = bookDetails.ImageURL,
                ISBN = bookDetails.ISBN,
                IsBorrowed = bookDetails.IsBorrowed,
                CategoryId = bookDetails.CategoryId,
                PublisherId = bookDetails.PublisherId,
                AuthorId = bookDetails.Authors_Books.Select(n => n.AuthorId).ToList(),
            };

            var bookDropDown = await _service.GetNewBookDropdownsValues();
            ViewBag.Authors = new SelectList(bookDropDown.Authors, "Id", "FullName");
            ViewBag.Publishers = new SelectList(bookDropDown.Publishers, "Id", "Name");
            ViewBag.Categories = new SelectList(bookDropDown.Categories, "Id", "Name");

            await _service.DeleteNewBookAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Projekt-Biblioteka/Controllers/CategoryController.cs
using Projekt_Biblioteka.Data.Services;
using Projekt_Biblioteka.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Projekt_Biblioteka.Data.Static;
using Microsoft.AspNetCore.Authorization;

namespace Projekt_Biblioteka.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class CategoryController : Controller
    {
        private readonly ICategoryService _service;

        public CategoryController(ICategoryService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index()
        {
            var allCategories = await _service.GetAllAsync();
            return View(allCategories);
        }

        //GET: category/details
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var categoryDetails = await _service.GetCategoryByIdAsync(id);
            if (categoryDetails == null) return View("NotFound");
            return View(categoryDetails);
        }

        //GET: category/create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Category category)
        {
            if (!ModelState.IsValid) return View(category);

            await _service.AddAsync(category);
            return RedirectToAction(nameof(Index));
        }

        //GET: category/edit
        public async Task<IActionResult> Edit(int id)
        {
            var categoryDetails = await _service.GetCategoryByIdAsync(id);
            if (categoryDetails == null) return View("NotFound");
            return View(categoryDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, Category category)
        {
            if (!ModelState.IsValid) return View(category);

            if (id == category.Id)
            {
                await _service.UpdateAsync(id, category);
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        //GET: category/delete
        public async Task<IActionResult> Delete(int id)
        {
            var categoryDetails = await _service.GetCategoryByIdAsync(id);
            if (categoryDetails == null) return View("NotFound");
            return View(categoryDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeletePost(int id)
        {
            var categoryDetails = await _service.GetCategoryByIdAsync(id);
            if (categoryDetails == null) return View("NotFound");

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Projekt-Biblioteka/Controllers/OrderController.cs
using Projekt_Biblioteka.Data.Cart;
using Projekt_Biblioteka.Data.Services;
using Projekt_Biblioteka.Data.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using System.Threading.Tasks;
using Projekt_Biblioteka.Data.Static;

namespace Projekt_Biblioteka.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private readonly IBookService _bookService;
        private readonly BookCart _bookCart;
        private readonly IOrderService _orderService;

        public OrderController(IBookService bookService, BookCart bookCart, IOrderService orderService)
        {
            _bookService = bookService;
            _bookCart = bookCart;
            _orderService = orderService;
        }

        public async Task<IActionResult> Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);

            var orders = await _orderService.GetOrdersByUserIdAndRoleAsync(userId, userRole);
            return View(orders);
        }
        
        //BookCart
        public IActionResult BookCart()
        {
            var items = _bookCart.GetBookCartItems();
            _bookCart.BookCartItems = items;

            var response = new BookCartVM()
            {
                bookCart = _bookCart
            };

            return View(response);
        }
        //Add item
        public async Task<RedirectToActionResult> AddItemToBookCart(int id)
        {
            var item = await _bookService.GetBookByIdAsync(id);

            if (item != null)
            {
                _bookCart.AddItemToCart(item);
            }
            return RedirectToAction(nameof(BookCart));
        }
        //Remove item
        public async Task<IActionResult> RemoveItemFromBookCart(int id)
        {
            var item = await _bookService.GetBookByIdAsync(id);

            if (item != null)
            {
                _bookCart.RemoveItemFromCart(item);
            }
            return RedirectToAction(nameof(BookCart));
        }

        //CompleteOrder
        public async Task<IActionResult> CompleteOrder()
        {
            var items = _bookCart.GetBookCartItems();
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userEmailAddress = User.FindFirstValue(ClaimTypes.Email);

            await _orderService.StoreOrderAsync(items, userId, userEmailAddress);
            await _bookCart.ClearBookCartAsync();
            foreach (var borrow in items)
            {
                await _bookCart.BorrowedStatus(borrow);
            }

            return View("CompleteOrder");
        }
    }
}

Projekt-Biblioteka/Views/Shared/NotFound.cshtml
<div class="row">
    <div class="col-md-6 offset-3 alert alert-light text-center ">
        <h2>Nic nie znaleziono</h2>
        <p>Kliknij przycisk poniżej, aby przejść do Strony Głównej</p>
        <hr />
        <p>
            <a asp-controller="Book" asp-action="Index" class="btn btn-dark">Strona Główna</a>
        </p>
    </div>
</div>

Projekt-Biblioteka/Views/Shared/_CreateButton.cshtml
@model string;

<div style="position: fixed; right: 50px; bottom: 70px;" class="text-white">
    <a asp-controller="@Model" asp-action="Create" class="btn btn-success">
        <i class="bi bi-plus-circle"></i> Dodaj
    </a>
</div>

Projekt-Biblioteka/Views/Shared/_Identity.cshtml
@inject UserManager<AppUser> UserManager;

@if (!User.Identity.IsAuthenticated)
{
    <a class="btn btn-outline-success my-2 my-sm-0" asp-controller="Account" asp-action="Login">
        <i class="bi bi-box-arrow-in-right"></i> Zaloguj się
    </a>
    <span style="padding: 5px;"></span>
    <a class="btn btn-outline-success my-2 my-sm-0" asp-controller="Account" asp-action="Register">
        <i class="bi bi-box-arrow-in-right"></i> Zarejestruj się
    </a>
}
else
{
    <div class="dropdown">
        <button class="btn btn-outline-success dropdown-toggle" type="button" id="profile-btn" data-toggle="dropdown"
                aria-expanded="false">
            <i class="bi bi-person-badge"></i> Witaj @UserManager.GetUserName(User)
        </button>
        <ul class="dropdown-menu" aria-labelledby="profile-btn">
            <li>
                <a class="dropdown-item" asp-controller="Order" asp-action="Index">
                    <i class="bi bi-list"></i> Zamówienia
                </a>
            </li>
            @if (User.IsInRole("Admin"))
            {
                <li>
                    <a class="dropdown-item" asp-controller="Account" asp-action="Readers">
                        <i class="bi bi-people"></i> Users
                    </a>
                </li>
            }
        </ul>
    </div>
    <span style="padding: 5px;"></span>
    <form asp-controller="Account" asp-action="Logout">
        <button class="btn btn-outline-danger my-2 my-sm-0">
            <i class="bi bi-box-arrow-in-right"></i> Wyloguj się
        </button>
    </form>
}

Projekt-Biblioteka/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Biblioteka</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Book" asp-action="Index">Biblioteka</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index">Katalog</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Kategorie
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Details" asp-route-id="1">Fantasy</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Details" asp-route-id="2">Horror</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Details" asp-route-id="3">Biografia</a>
                            </div>
                        </li>
                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="bi bi-gear"></i> Zarządzanie
                                </a>

                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Create">Dodaj Książkę</a>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Kategorie</a>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Author" asp-action="Index">Autorzy</a>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Publisher" asp-action="Index">Wydawnictwa</a>
                                </div>
                            </li>
                        }
                    </ul>
                    <form class="form-inline my-2 my-lg-0" asp-controller="Book" asp-action="Filter" style="padding-right: 25px;">
                        <input name="searchString" type="text" class="form-control" placeholder="Szukaj książki lub autora..." aria-label="Recipient's username" aria-describedby="button-addon2">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="bi bi-search"></i></button>
                    </form>
                    <ul class="navbar-nav">
                        @await Component.InvokeAsync("BookCartSummary")
                    </ul>
                    <partial name="_Identity.cshtml" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Biblioteka 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>